### ISSUE TITLE
UnboundLocalError: local variable 'encoding' referenced before assignment

### ISSUE THREAD

**Issue by wizeman** [gaubert/gmvault#206]
When testing branch `gmv-1.9.1` (up to commit ffc31893a687451df24f448624991ef60c42763e), I ran across this error:

```
Process email num 512016 (imap_id:585118) from 2013-03.
metadata info collected: {u'X-GM-MSGID': 1430246627622484413, u'INTERNALDATE': datetime.datetime(2013, 3, 22, 23, 57, 55), u'X-GM-LABELS': [u'Entrada', u'lists/zfs-discuss'], u'SEQ': 512017, u'FLAGS': (u'\\Seen',), u'BODY[HEADER.FIELDS (MESSAGE-ID SUBJECT X-GMAIL-RECEIVED)]': u'Message-ID: <514CD3D0.3000308@oracle.com>\r\nSubject: [zfs-discuss] LAST CALL: zfs-discuss is moving Sunday, March 24, 2013\r\n\r\n', u'X-GM-THRID': 1430246627622484413}

Cannot read file 1430246627622484413.meta. Try to fetch the data again
Traceback (most recent call last):
  File "/nix/store/104ggc2aix8x51namm446c85q4rrac55-python2.7-gmvault-1.9.1-git-2015-05-13/lib/python2.7/site-packages/gmv/gmvault.py", line 332, in check_email_on_disk
    return a_gstorer.unbury_metadata(a_id, a_dir)
  File "/nix/store/104ggc2aix8x51namm446c85q4rrac55-python2.7-gmvault-1.9.1-git-2015-05-13/lib/python2.7/site-packages/gmv/gmvault_db.py", line 656, in unbury_metadata
    metadata = json.load(f)
  File "/nix/store/pbi1lgank10fy0xpjckbdpgacqw34dsz-python-2.7.9/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/nix/store/pbi1lgank10fy0xpjckbdpgacqw34dsz-python-2.7.9/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/nix/store/pbi1lgank10fy0xpjckbdpgacqw34dsz-python-2.7.9/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/pbi1lgank10fy0xpjckbdpgacqw34dsz-python-2.7.9/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Get Data for 1430246627622484413.
Storing on disk data for 1430246627622484413
Error. The passed string is a unicode string and not a byte string
Error: local variable 'encoding' referenced before assignment. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/nix/store/104ggc2aix8x51namm446c85q4rrac55-python2.7-gmvault-1.9.1-git-2015-05-13/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/nix/store/104ggc2aix8x51namm446c85q4rrac55-python2.7-gmvault-1.9.1-git-2015-05-13/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 665, in _sync
    restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/nix/store/104ggc2aix8x51namm446c85q4rrac55-python2.7-gmvault-1.9.1-git-2015-05-13/lib/python2.7/site-packages/gmv/gmvault.py", line 625, in sync
    self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
  File "/nix/store/104ggc2aix8x51namm446c85q4rrac55-python2.7-gmvault-1.9.1-git-2015-05-13/lib/python2.7/site-packages/gmv/gmvault.py", line 588, in _sync_emails
    imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
  File "/nix/store/104ggc2aix8x51namm446c85q4rrac55-python2.7-gmvault-1.9.1-git-2015-05-13/lib/python2.7/site-packages/gmv/gmvault.py", line 546, in _common_sync
    handle_sync_imap_error(error, the_id, self.error_report, self.src) #do everything in this handler
  File "/nix/store/104ggc2aix8x51namm446c85q4rrac55-python2.7-gmvault-1.9.1-git-2015-05-13/lib/python2.7/site-packages/gmv/gmvault.py", line 154, in handle_sync_imap_error
    raise the_exception
UnboundLocalError: local variable 'encoding' referenced before assignment

=== End of Exception traceback ===
```

Any ideas?

**Comment by gaubert** [comment]
@wizeman Thanks I fixed it. 1.9.1 was not yet ready. It is expected to be released in two weeks.

**Comment by wizeman** [comment]
Using the latest commit (37c6904d1d6e957a1b8f506a843d87406509fe77) in branch `gmv-1.9.1`, I am still seeing this error:

```
Aug 25 19:16:54 homeserv gmvault[14457]: Process email num 512015 (imap_id:585117) from 2013-03.
Aug 25 19:16:54 homeserv gmvault[14457]: Process email num 512016 (imap_id:585118) from 2013-03.
Aug 25 19:16:54 homeserv gmvault[14457]: Error: local variable 'encoding' referenced before assignment.
Aug 25 19:16:54 homeserv gmvault[14457]: === Exception traceback ===
Aug 25 19:16:54 homeserv gmvault[14457]: Traceback (most recent call last):
Aug 25 19:16:54 homeserv gmvault[14457]: File "/nix/store/ig2hnmr2wv4wg3cnlzjvq2nim356yikd-python2.7-gmvault-1.9.1-git-2015-08-25/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 746, in run
Aug 25 19:16:54 homeserv gmvault[14457]: self._sync(args, credential)
Aug 25 19:16:54 homeserv gmvault[14457]: File "/nix/store/ig2hnmr2wv4wg3cnlzjvq2nim356yikd-python2.7-gmvault-1.9.1-git-2015-08-25/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 665, in _sync
Aug 25 19:16:54 homeserv gmvault[14457]: restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
Aug 25 19:16:54 homeserv gmvault[14457]: File "/nix/store/ig2hnmr2wv4wg3cnlzjvq2nim356yikd-python2.7-gmvault-1.9.1-git-2015-08-25/lib/python2.7/site-packages/gmv/gmvault.py", line 625, in sync
Aug 25 19:16:54 homeserv gmvault[14457]: self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
Aug 25 19:16:54 homeserv gmvault[14457]: File "/nix/store/ig2hnmr2wv4wg3cnlzjvq2nim356yikd-python2.7-gmvault-1.9.1-git-2015-08-25/lib/python2.7/site-packages/gmv/gmvault.py", line 588, in _sync_emails
Aug 25 19:16:54 homeserv gmvault[14457]: imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
Aug 25 19:16:54 homeserv gmvault[14457]: File "/nix/store/ig2hnmr2wv4wg3cnlzjvq2nim356yikd-python2.7-gmvault-1.9.1-git-2015-08-25/lib/python2.7/site-packages/gmv/gmvault.py", line 546, in _common_sync
Aug 25 19:16:54 homeserv gmvault[14457]: handle_sync_imap_error(error, the_id, self.error_report, self.src) #do everything in this handler
Aug 25 19:16:54 homeserv gmvault[14457]: File "/nix/store/ig2hnmr2wv4wg3cnlzjvq2nim356yikd-python2.7-gmvault-1.9.1-git-2015-08-25/lib/python2.7/site-packages/gmv/gmvault.py", line 154, in handle_sync_imap_error
Aug 25 19:16:54 homeserv gmvault[14457]: raise the_exception
Aug 25 19:16:54 homeserv gmvault[14457]: UnboundLocalError: local variable 'encoding' referenced before assignment
Aug 25 19:16:54 homeserv gmvault[14457]: === End of Exception traceback ===
```

I know version 1.9.1 is not released yet, but I am trying to use it because none of the previous versions work for me anymore.

**Comment by gaubert** [comment]
@wizeman Ok thanks. I think I have corrected the issue as your subject was already in unicode.
Anyway can I ask to pull the latest version of gmv-1.9.1 and make a new test and report any problems.

Thanks

**Comment by wizeman** [comment]
@gaubert Unfortunately even after updating to commit b275305cbe108dc667a56c9c8bcf8220c3860d74, I am still seeing this error.

Last messages from the log:

```
[2015-08-27 12:40]:CRITICAL:gmvault:Process email num 512016 (imap_id:585118) from 2013-03.
[2015-08-27 12:40]:DEBUG:gmvault:metadata info collected: {u'X-GM-MSGID': 1430246627622484413, u'INTERNALDATE': datetime.datetime(2013, 3, 22, 23, 57, 55), u'X-GM-LABELS': [u'Entrada', u'lists/zfs-discuss'], u'SEQ': 512017, u'FLAGS': (u'\
\Seen',), u'BODY[HEADER.FIELDS (MESSAGE-ID SUBJECT X-GMAIL-RECEIVED)]': u'Message-ID: <514CD3D0.3000308@oracle.com>\r\nSubject: [zfs-discuss] LAST CALL: zfs-discuss is moving Sunday, March 24, 2013\r\n\r\n', u'X-GM-THRID': 143024662762248
4413}                                                                                                                                                                                                                                        

[2015-08-27 12:40]:ERROR:gmvault:Cannot read file 1430246627622484413.meta. Try to fetch the data again
Traceback (most recent call last):
  File "/nix/store/hj56c2brkwxw9qaiwgvrw7n2g40qzb15-python2.7-gmvault-1.9.1-git-2015-08-27/lib/python2.7/site-packages/gmv/gmvault.py", line 332, in check_email_on_disk
    return a_gstorer.unbury_metadata(a_id, a_dir)
  File "/nix/store/hj56c2brkwxw9qaiwgvrw7n2g40qzb15-python2.7-gmvault-1.9.1-git-2015-08-27/lib/python2.7/site-packages/gmv/gmvault_db.py", line 648, in unbury_metadata
    metadata = json.load(f)
  File "/nix/store/lj6vx7f7pwv0qh1pg8xz40mxs5112zs1-python-2.7.10/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/nix/store/lj6vx7f7pwv0qh1pg8xz40mxs5112zs1-python-2.7.10/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/nix/store/lj6vx7f7pwv0qh1pg8xz40mxs5112zs1-python-2.7.10/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/lj6vx7f7pwv0qh1pg8xz40mxs5112zs1-python-2.7.10/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[2015-08-27 12:40]:DEBUG:gmvault:Get Data for 1430246627622484413.
[2015-08-27 12:40]:DEBUG:gmvault:Storing on disk data for 1430246627622484413
[2015-08-27 12:40]:DEBUG:gmvault_utils:Guess encoding
[2015-08-27 12:40]:DEBUG:gmvault_utils:Exception: Error. The passed string is a unicode string and not a byte string
[2015-08-27 12:40]:CRITICAL:gmv:Error: local variable 'encoding' referenced before assignment. 

[2015-08-27 12:40]:CRITICAL:gmv:=== Exception traceback ===
[2015-08-27 12:40]:CRITICAL:gmv:Traceback (most recent call last):
  File "/nix/store/hj56c2brkwxw9qaiwgvrw7n2g40qzb15-python2.7-gmvault-1.9.1-git-2015-08-27/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 746, in run
    self._sync(args, credential)
  File "/nix/store/hj56c2brkwxw9qaiwgvrw7n2g40qzb15-python2.7-gmvault-1.9.1-git-2015-08-27/lib/python2.7/site-packages/gmv/gmv_cmd.py", line 665, in _sync
    restart = args['restart'], emails_only = args['emails_only'], chats_only = args['chats_only'])
  File "/nix/store/hj56c2brkwxw9qaiwgvrw7n2g40qzb15-python2.7-gmvault-1.9.1-git-2015-08-27/lib/python2.7/site-packages/gmv/gmvault.py", line 625, in sync
    self._sync_emails(imap_req, compress = compress_on_disk, restart = restart)
  File "/nix/store/hj56c2brkwxw9qaiwgvrw7n2g40qzb15-python2.7-gmvault-1.9.1-git-2015-08-27/lib/python2.7/site-packages/gmv/gmvault.py", line 588, in _sync_emails
    imap_ids = self._common_sync(timer, "email", imap_req, compress, restart)
  File "/nix/store/hj56c2brkwxw9qaiwgvrw7n2g40qzb15-python2.7-gmvault-1.9.1-git-2015-08-27/lib/python2.7/site-packages/gmv/gmvault.py", line 546, in _common_sync
    handle_sync_imap_error(error, the_id, self.error_report, self.src) #do everything in this handler
  File "/nix/store/hj56c2brkwxw9qaiwgvrw7n2g40qzb15-python2.7-gmvault-1.9.1-git-2015-08-27/lib/python2.7/site-packages/gmv/gmvault.py", line 154, in handle_sync_imap_error
    raise the_exception
UnboundLocalError: local variable 'encoding' referenced before assignment

[2015-08-27 12:40]:CRITICAL:gmv:=== End of Exception traceback ===
```

**Comment by gaubert** [comment]
@wizeman Ok I need to check that I have correctly fixed the issue. Give me a couple of days because I am busy.

**Comment by gaubert** [comment]
@wizeman Ok I have checked and there are two problems. First, it seems that Gmvault has problems reading 1430246627622484413.meta. Is it corrupted, has got an encoding issue ? Could you if possible and not personal send me that metadata file and the corresponding email. I would like to do some tests with it to define how to react in case of issue. I could delete the metadata file and it will be re-created for instance.

Now Gmvault even if it cannot read the metadata file should continue processing emails. There was a bug with guess_encoding that I have fix. Could you try again without deleting the metadata file.
It is commit a5727e3f9d56cc5876e5aa04479cafe5777a5287. Pls activate debugging info and send me the console output.

Hopefully it should work now.

**Comment by gaubert** [comment]
close it now
