### ISSUE TITLE
Restore fails with error 'TypeError: %d format: a number is required, not set'

### ISSUE THREAD

**Issue by emmawinston** [gaubert/gmvault#217]
Hi, 

I'm in the process of backing up a decade's worth of emails using gmvault. Export worked absolutely fine, I left the program running overnight to restore the mails to my backup account, and it's about 75% done. However, I can't get it to go any further - it stopped with an error some time during the night, and --resume gives the same error at the same point.

I'm using OS X Yosemite, and running gmvault 1.9 (downloaded from gmvault.org last night). 

Any suggestions would be very much appreciated.

EDITED to add: I've emailed a full debug log to you with the issue number referenced in the title. Hope this is useful rather than annoying!

```
Aug 11 15:42:11 Emmas-MBP.home gmv_runner[43894] <Notice>: Applying labels to the current batch of emails.
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>: Error: %d format: a number is required, not set. 
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>: 
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>: === Exception traceback ===
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>: Traceback (most recent call last):
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>:   File "gmv/gmv_cmd.pyc", line 745, in run
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>:   File "gmv/gmv_cmd.pyc", line 621, in _restore
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>:   File "gmv/gmvault.pyc", line 882, in restore
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>:   File "gmv/gmvault.pyc", line 1146, in restore_emails
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>: TypeError: %d format: a number is required, not set
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>: 
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>: === End of Exception traceback ===
Aug 11 15:42:13 Emmas-MBP.home gmv_runner[43894] <Notice>: 
```

**Comment by gaubert** [comment]
yep there is a bug in 1.9 that I have solved in 1.9.1 I believe but this requires additional testing. 
I have created a new 1.9.1 version for macosX here: https://www.dropbox.com/s/oqxlqmghs0pgydw/gmvault-v1.9.1-macosx-intel.tar.gz?dl=0

Could you test it for me. I have also change the installation for mac osx. Just untar the dir and launch gmvault. It is an executable and much simpler. Let me know if it has been working for you

**Comment by emmawinston** [comment]
Thank you for this. Unfortunately the executable exits immediately on opening with the following error: 

```
Emmas-MBP:~ emmawinston$ /Users/emmawinston/Desktop/gmvault-v1.9.1/gmvault ; exit;

gmvault: error: too few arguments

usage: gmvault [-h] [-v] {sync,restore,check,export} ...

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit

subcommands:
  {sync,restore,check,export}
                        valid subcommands.
    sync                synchronize with a given gmail account.
    restore             restore gmvault-db to a given email account.
    check               check and clean the gmvault-db disk database.
    export              Export the gmvault-db database to another format.

Examples:

a) Get help for each of the individual commands

#> gmvault sync -h
#> gmvault restore --help
#> gmvault check -h
#> gmvault export -h


logout

[Process completed]
```
Any ideas?

**Comment by gaubert** [comment]
@emmawinston you need to run it with the restore command

```
Emmas-MBP:~ emmawinston$ cd /Users/emmawinston/Desktop/gmvault-v1.9.1/
Emmas-MBP:~ emmawinston$ ./gmvault restore emailwhereIwanttorestore@gmail.com --debug
....
```

Let me know how it goes.

**Comment by emmawinston** [comment]
I can't run anything because the program immediately terminates when the executable is opened. I don't get the opportunity to run any commands. I had no problem doing so in the non-executable earlier version.

**Comment by gaubert** [comment]
@emmawinston Have a look at the commands I sent you. You need to open a terminal and in the terminal type the cd command and then the ./gmvault command

Alternatively in your terminal you could also type:
```
Emmas-MBP:~ emmawinston$ /Users/emmawinston/Desktop/gmvault-v1.9.1/gmvault restore myemail@gmail.com --debug
```

Thanks

**Comment by emmawinston** [comment]
Oh, apologies, I didn't realise it was run in the same way as the non-executable version. 

Still getting a failure message. Here it is:

```
Applying labels [u'\\Draft']
Before to store labels (\Draft)
After storing labels (\Draft). Operation time = 0.281767129898 s.
ret = NO
data=['System Error (Failure)']
Problem when applying labels \Draft to the following ids: set([67826, 67870])
Error: Cannot add Labels (\Draft) to emails with uids set([67826, 67870]). Error:['System Error (Failure)']. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 750, in run
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 625, in _restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 900, in restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 1169, in restore_emails
LabelError: Cannot add Labels (\Draft) to emails with uids set([67826, 67870]). Error:['System Error (Failure)']

=== End of Exception traceback ===
```

**Comment by nicosilber** [comment]
I had the same error!!
I am running --debug now so that I can send it to @gaubert

**Comment by gaubert** [comment]
@emmawinston @nicosilber Ok let's try again. I didn't copy the right version yesterday sorry !
https://www.dropbox.com/s/e1apv28wl5trigh/u1-gmvault-v1.9.1-macosx-intel.tar.gz?dl=0

Let me know if it fixes your issues.

Thanks

**Comment by nicosilber** [comment]
Hello gaubert...this new version you just send is for MAC?? I have windows 10....I dont know how to install a .tar.gz,...can you send an .exe?

**Comment by gaubert** [comment]
@emmawinston this has been fixed in the current 1.9.1

**Comment by gaubert** [comment]
fixed will close it now. I am in testing validation mode before launching the new version.

**Comment by emmawinston** [comment]
I'm still getting the error mentioned in my previous comment:

```Applying labels [u'\\Draft']
Before to store labels (\Draft)
After storing labels (\Draft). Operation time = 0.281767129898 s.
ret = NO
data=['System Error (Failure)']
Problem when applying labels \Draft to the following ids: set([67826, 67870])
Error: Cannot add Labels (\Draft) to emails with uids set([67826, 67870]). Error:['System Error (Failure)']. 

=== Exception traceback ===
Traceback (most recent call last):
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 750, in run
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmv_cmd", line 625, in _restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 900, in restore
  File "/Users/gaubert/Dev/projects/gmvault-1.8.2/build/gmvault/out00-PYZ.pyz/gmv.gmvault", line 1169, in restore_emails
LabelError: Cannot add Labels (\Draft) to emails with uids set([67826, 67870]). Error:['System Error (Failure)']

=== End of Exception traceback ===```


Where can I download the newest version? The one on the website is still listed as 1.9 and the one in your dropbox link is expired.

**Comment by gaubert** [comment]
@emmawinston if you are on a mac you can try this one but I have not finished to package it: https://www.dropbox.com/s/oqxlqmghs0pgydw/gmvault-v1.9.1-macosx-intel.tar.gz?dl=0

Let me know how it goes

**Comment by Gmail2016** [comment]
@gaubert - Please help me. I am getting the error below. I downloaded the 9.1 version, I was able to restore a few emails but then have been getting this error. I need to restore my emails in 2 days as my office wants to reformat all computers and after reformatting I do not know if I'll be able to save the gmvault files. I am using a windows OS.

![image](https://cloud.githubusercontent.com/assets/16752052/12409519/de40c742-be90-11e5-80e5-3768917e4ffb.png)

**Comment by fmoyses** [comment]
@gaubert, Hi!

Could you deliver us a windows working package of the 1.9.1 version? I`m having this same error and the dropbox version is for mac only.

Thanks.
