### ISSUE TITLE
oauth2 fails with urlopen error

### ISSUE THREAD

**Issue by bjnath** [gaubert/gmvault#285]
I'm getting oauth2 errors when I sign in, but it's showing a message that I don't think has been reported before:

    Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>.

I press ENTER, give gmvault permission, and copy the verification code as instructed.
The response is:        

    Error: Problems when trying to connect to Google oauth2 endpoint: https://accounts.google.com/o/oauth2/token.
    Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>.

    === Exception traceback ===
    Traceback (most recent call last):
      File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.gmv_cmd", line 743, in run
      File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 235, in     get_credential
      File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 387, in get_oauth2_credential
      File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 342, in _get_oauth2_tokens
      File "c:\Users\toto\Dev\gmvault\build\gmv_runner\out00-PYZ.pyz\gmv.credential_utils", line 306, in _get_authorization_tokens
    URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

    === End of Exception traceback ===

The oauth2 file in .gmvault isn't touched.
I'm running 1.9.1 on Windows 10.

Thank you for this program and for your help!

**Comment by gaubert** [comment]
yes it is fixed in 1.9.2 and I will release soon a new version

**Comment by gaubert** [comment]
@bjnath you can test the latest beta version here (beta windows and mac os x package available):
https://www.dropbox.com/sh/d5ceo77juacr03y/AACUGcTt6Um-6j6JmBizGPA2a?dl=0

or from the branch gmv-1.9.2

Help required for testing to see if I missed something. Many thanks for the testing.

**Comment by bjnath** [comment]
Thank you for the update! The operation completed without the error message, and I saw my most recent email in the backup. 

One thing seemed strange: running the gmvault sync --resume command over again gave me the same messages (Process email num 0...). Tried it a few times, always the same.  Of course, I don't normally do this, so it may be expected behavior.

 

 Thank you again.

 

-----Original Message-----

**Comment by gaubert** [comment]
@bjnath Ok will test the resume to be sure it is working. Thanks.

**Comment by AlexKasaku** [comment]
This issue has been fixed for me in the 1.9.2 beta!

**Comment by gaubert** [comment]
@atppp version 1.9.2-beta-1 available for test and fixing many additional problems (especially in the restore). Please test it and let me know if this is fine within 6 days. Many thanks.

https://www.dropbox.com/sh/d5ceo77juacr03y/AACUGcTt6Um-6j6JmBizGPA2a?dl=0

**Comment by gaubert** [comment]
@AlexKasaku Thanks for testing 1.9.2-beta. I released an updated version.

**Comment by bjnath** [comment]
Still seeing the behavior where some of the emails appear to be reprocessed when I run sync --resume more than once.

All runs after the first give the same gmail id in "Restart from gmail id." It's different from the first.

The emails in the second run and after are a subset of the emails in the first. 

The imap ids for email num 0, 1, 2, ... are not strictly increasing; not sure if this is significant.

 

-----Original Message-----

**Comment by gaubert** [comment]
@bjnath Thanks I don't see that behaviour, could you use the --debug and send me the logs by email for instance.

Many thanks for the testing !

**Comment by flop25** [comment]
Hello
the 1.9.2 has still  not been released and i'm getting the same error on 1.9.1 windows 10 64b
do you need more testing for 1.9.2? may i try a 1.9.2 beta?

**Comment by velodani** [comment]
google lead me to this thread since i have same troubles like bjnath in the first place.
But also with the beta you linked here, i have the same errors when i try the command 
gmvault restore -t quick mail@gmail.com

**Comment by genetrader** [comment]
1.9.2-beta1 working like a charm for me - picking up and syncing where it left off.

Thank you guys so much!!!

Where is your donate link?  Let me at least buy the team a few cups of coffee...

**Comment by genetrader** [comment]
For those looking for the link - the BETA link is on this thread and open - its a Dropbox link listed above.

**Comment by jrichardson0** [comment]
I am getting this error as of today but I have never had it in the past. I tried the beta listed above and I do see the error. Will another update be available in the future, or is there anything I can do to help make it work? Thank you so much for your efforts with this application!
